### ISSUE TITLE
右侧文字如果也能设置点击事件就好了，就可以代替titleBar了

### ISSUE THREAD

**Issue by fxjzzyo** [DMingOu/OptionBarView#3]
我想用这个控件做标题栏，中间标题，左边返回按钮都可以满足需求。
可惜的是，右侧按钮如果是文字，如“完成”，的情况下，该控件就不能为右侧文字设置点击事件监听了。只能用图片。

**Comment by DMingOu** [comment]
可以参考下这样设置：

        opv3 = findViewById(R.id.opv_3);
        opv3.setSplitMode(true);
        opv3.setOnOptionItemClickListener(new OptionBarView.OnOptionItemClickListener() {
            @Override
            public void leftOnClick() {
            }
            @Override
            public void centerOnClick() {
            }

            @Override
            public void rightOnClick() {
                Toast.makeText(MainActivity.this,"点击了右侧标题3",Toast.LENGTH_LONG).show();
            }
        });

![image-20201119085920313](http://picbed-dmingou.oss-cn-shenzhen.aliyuncs.com/img/image-20201119085920313.png)

**Comment by fxjzzyo** [comment]
> 可以参考下这样设置：
> 
> ```
>     opv3 = findViewById(R.id.opv_3);
>     opv3.setSplitMode(true);
>     opv3.setOnOptionItemClickListener(new OptionBarView.OnOptionItemClickListener() {
>         @Override
>         public void leftOnClick() {
>         }
>         @Override
>         public void centerOnClick() {
>         }
> 
>         @Override
>         public void rightOnClick() {
>             Toast.makeText(MainActivity.this,"点击了右侧标题3",Toast.LENGTH_LONG).show();
>         }
>     });
> ```
> 
> ![image-20201119085920313](https://camo.githubusercontent.com/d41d360b0a4d115129bfa29bb7a832a9d8e3e3ca972430d3cd65beefac3ce137/687474703a2f2f7069636265642d646d696e676f752e6f73732d636e2d7368656e7a68656e2e616c6979756e63732e636f6d2f696d672f696d6167652d32303230313131393038353932303331332e706e67)

感谢回答。我的意思是，右侧文字哦，不是图片。右侧的图片是这样点击的，但是文字没有点击监听。这个OnOptionItemClickListener接口是监听了最右侧的View 吧，而文字是倒数第二个View。

**Comment by DMingOu** [comment]
![20201120_144344](https://user-images.githubusercontent.com/47693985/99767954-f434cd80-2b3e-11eb-888d-3ca67c3febaf.gif)

如上图，目前的OpionBarView是能实现监听右侧的区域的点击事件的，没有分第几个View。

但如果说要作为TitleBar使用的话，可能需要进一步的扩展。

**Comment by fxjzzyo** [comment]
> ![20201120_144344](https://user-images.githubusercontent.com/47693985/99767954-f434cd80-2b3e-11eb-888d-3ca67c3febaf.gif)
> 
> 如上图，目前的OpionBarView是能实现监听右侧的区域的点击事件的，没有分第几个View。
> 
> 但如果说要作为TitleBar使用的话，可能需要进一步的扩展。

哦哦，是的，我又试了一遍可以了。之前是我是同时把rightviewtype设置了image,导致右侧文字一直没法靠到最右边。感谢，这个控件很好用。
